version: '3'
services:
  worker:
    build:
      dockerfile: worker/Dockerfile
      context: .
    ports:
      - "5000:5000"
  scheduler:
    build:
      dockerfile: scheduler/Dockerfile
      context: .
    ports:
      - "3010:3010"
  web:
    build:
      dockerfile: web/Dockerfile
      context: .
    ports:
      - "4000:3000"
  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./.mongodb:/data/db
