[package]
name = "darkforce_worker"
version = "0.1.0"
authors = ["Joatin Granlund <granlundjoatin@gmail.com>", "lykata"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.21", features = ["full"] }
slog = "2.5.2"
sloggers = "1.0.1"
failure = "0.1.8"